name: .NET Build & Test All

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: |
        dotnet restore UCLN-BCNN/UCLN-BCNN

    - name: Build
      run: |
        dotnet build UCLN-BCNN/UCLN-BCNN --no-restore
